### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by dcblogdev** [themsaid/ibis#1]
First, Thanks for releasing this great tool!

I've installed globally using

```
composer global require themsaid/ibis
```

Then went into an empty directory and ran:

```
ibis init
```

I then get:

```
PHP Warning:  require(/Users/dave/.composer/vendor/themsaid/ibis/vendor/autoload.php): failed to open stream: No such file or directory in /Users/dave/.composer/vendor/themsaid/ibis/ibis on line 10

Warning: require(/Users/dave/.composer/vendor/themsaid/ibis/vendor/autoload.php): failed to open stream: No such file or directory in /Users/dave/.composer/vendor/themsaid/ibis/ibis on line 10
PHP Fatal error:  require(): Failed opening required '/Users/dave/.composer/vendor/themsaid/ibis/vendor/autoload.php' (include_path='.:/usr/local/Cellar/php/7.4.11/share/php/pear') in /Users/dave/.composer/vendor/themsaid/ibis/ibis on line 10

Fatal error: require(): Failed opening required '/Users/dave/.composer/vendor/themsaid/ibis/vendor/autoload.php' (include_path='.:/usr/local/Cellar/php/7.4.11/share/php/pear') in /Users/dave/.composer/vendor/themsaid/ibis/ibis on line 10

```

Have I missed a step?

**Comment by owenvoke** [comment]
It looks like it's expecting to be run in the same directory (see the [`ibis` binary](https://github.com/themsaid/ibis/blob/ae91b1c3507f35b6e25ed7dcfe0586965e65e611/ibis#L10)).

I've opened #2 which should resolve this.

**Comment by dcblogdev** [comment]
Yep just made the change locally and can confirm that does work 👍

**Comment by liorchamla** [comment]
I'm sorry, because this is an other issue but, did u all got an error because of the fonts TTF not found in the folder when building your first book ? I also have an other error when creating the sample (because no PDF file is found in the export folder). I wonder if it is only on my computer or if u all have it too ?

**Comment by dcblogdev** [comment]
yeah I just commented out the fonts from the config:

```
'fonts' => [
        //'calibri' => 'Calibri-Regular.ttf',
        //'times' => 'times-regular.ttf',
    ],
```

This is useful if you want to use custom fonts.

**Comment by liorchamla** [comment]
Ok ! I believe you could close this PR so :)
