### ISSUE TITLE
Valet requirement

### ISSUE THREAD

**Issue by wishinghand** [themsaid/ibis#11]
Perfect project for me because I write everything in Markdown. However I just got finished updating everything Composer needed in order to finally install it and after `ibis init` I got the error: `Valet only supports the Mac operating system.` I'm trying to run this in WSL 2 on Windows 10. I checked the `composer.json` in the Ibis repo and don't see Laravel or Valet as a dependency, so I'm wondering if this is a side effect of my setup or a dependency of a dependency.

Any way to get this running on Windows or Linux?

**Comment by themsaid** [comment]
Ibis doesn't require Valet at all. I'm not sure where that error is coming from.

**Comment by wishinghand** [comment]
Super strange. I tried it on my work Macbook and it installs just fine. I can't imagine why Valet is being invoked on WSL.
