### ISSUE TITLE
Arabic letters

### ISSUE THREAD

**Issue by mostnour** [themsaid/ibis#12]
Hi, Mohamed Said, 

This is the first run through to keep in touch with you. 

I attempted to utilize Arabic letters in your task ibis, it is brilliant. 

In any case, is there any approach to set the direction from left to right when utilizing Arabic letters. 

Respects, 

Mostafa Gaber

**Comment by bmcminn** [comment]
Check out the `/assets/theme-[style].html` files. There is a light and dark theme, but you may be able to do something like `body { direction: rtl; }` to force RTL.

Thinking about how to fix this in the library through, I'm pretty sure an update could be done in the build process when Mpdf is leveraged to force RTL based on language using `$mpdf->SetDirectionality($config['direction'] ?? 'ltr');`.

An implicit LTR or RTL assignment based on language could be a cool feature on top of that with `$config['direction']` being a master override.

**Comment by mostnour** [comment]
Much obliged to you for your help. 

It is working at this point.

**Comment by themsaid** [comment]
Hey,

You can set the direction from the theme file yes.
