### ISSUE TITLE
Support for equations?

### ISSUE THREAD

**Issue by cscazorla** [themsaid/ibis#16]
Are you considering the idea of adding support for Latex formulas? For example

$\int_0^2 x^2dx$

**Comment by bmcminn** [comment]
You might checkout the discussion happening around #13 and #14 

This would give you the ability to add whatever forumla syntax you wanted, though you'd have to write the integration yourself or wait for someone to put a plugin together for it.

Either way this is one of the exact reasons I provided for adding and exposing life cycle hooks to the library.

**Comment by cscazorla** [comment]
Thanks!

**Comment by cscazorla** [comment]
Solved
