### ISSUE TITLE
Code Standard Enforcement

### ISSUE THREAD

**Issue by aaronsaray** [themsaid/ibis#32]
Hello - and thanks for creating this awesome project. :)

I noticed your `.php_cs` configuration file and the composer command.  However, I noticed some code could be out of standard. In addition, since everyone uses different code standard tools, they might not have php-cs-fixer installed globally.  That being said, I'd like to propose the following:

* Ensure all files are code standard compliant
* Add php-cs-fixer as a local project install as a composer dev dependency
* Add a script to composer to do a dry-run for people who'd like to review their code standard changes - and to be ran as part of CI
* Add a github action to run the code standard on pushes and pull requests

I'll submit a pull request with these suggested updates for your review.

**Comment by aaronsaray** [comment]
Thanks!

**Comment by themsaid** [comment]
thanks to you :)
