### ISSUE TITLE
Sample files

### ISSUE THREAD

**Issue by mattfletcher** [themsaid/ibis#6]
Is there any chance of including the input files in the example zip file, as well as the output files? Or perhaps a separate simple example of some of the features used?

**Comment by ericlbarnes** [comment]
Hi Matt, 

When you say "input files" are referring to adding some base markdown files in the content directory?

**Comment by mattfletcher** [comment]
Yeah, just some simple examples of how to make the sort of books you see in the zip file linked from the README.

**Comment by themsaid** [comment]
Done! Included sample content from my book https://github.com/themsaid/ibis/commit/020f6cea58c1e4e7119050c8b383960168125e71

Now the `init` command will create files inside the `content` directory and you can use `ibis build` to build a sample book right away.

**Comment by mattfletcher** [comment]
That's awesome, thank you very much!
