### ISSUE TITLE
How to include images

### ISSUE THREAD

**Issue by roelofjan-elsinga** [themsaid/ibis#7]
Thanks your this package, I've been eagerly waiting for it!

I'm wondering, how do I include images in my pages? Right now I'm trying:

```md
![Image title](images/filename.jpg)
```
Where I created a folder called "images" inside the "assets" folder. However, this image appears as broken in the PDF.

Thanks for your time!

**Comment by themsaid** [comment]
try `assets/images/filename.jpg`

**Comment by roelofjan-elsinga** [comment]
That works @themsaid, Thanks!

**Comment by xezpeleta** [comment]
Hi @themsaid 

Sadly, if we use the image path `assets/images/filename.jpg` breaks Github markdown visualization, which is useful to check everything is fine before building the pdf.

I've tried with absolute paths (`/assets/images/filename.jpg`). It works in GitHub but the images appear broken in the pdf.

Thanks for your work

**Comment by alexellis** [comment]
@xezpeleta @themsaid - can we get this into the README please? it's something I ran into with #28 and it's easy to just add it there.

**Comment by uyab** [comment]
A little bit hacky trick to have consistent preview between markdown editor and the generated PDF:
- Run `php -S localhost:80`. You can change 80 to another port.
- use local url to load image, e.g. `![](http://localhost:80/assets/img/dashboard.png)`
