### ISSUE TITLE
HTML based cover

### ISSUE THREAD

**Issue by eberkund** [themsaid/ibis#9]
Hi, this tool is really simple to use compared to some other solutions I have tried so kudos on that 👍 

It would be great if it could support HTML based covers rather than just a JPG. I am hoping I will be able to use this tool for creating reports and the cover I had in mind was more textual with a different layout. Are you open to supporting this use case? I imagine as this project grows, some more configuration options in `ibis.php` would allow it to support many different document use cases in addition to ebooks.

**Comment by themsaid** [comment]
Hey,

I'm ok with this yes :) Maybe add a config key in ibis.php to generate the cover from a cover.html file rather than an image. That's a really good idea I think.

**Comment by xezpeleta** [comment]
Would be great to easily add some info like version (tag) or date in that HTML cover!

**Comment by eberkund** [comment]
@xezpeleta dynamic dates can probably be done using functionality from the underlying mPDF library: https://mpdf.github.io/what-else-can-i-do/replaceable-aliases.html
